; ***
; *** Created by the Assignment File Wizard 3/25/2011 at 1:42 PM
; *** Copyright © Command Alkon Inc. 2002
; ***

[driver_settings]
ORA    U6.4
usys$ora_params=open cursors 400,disable packages,FV

[USER_3GL]
..\bin\cmdnet32.dll
..\bin\cmdutl32.dll
..\bin\cmdwid32.dll
..\bin\cmdout32.dll
..\bin\cmdtra32.dll
..\bin\cmdtrb32.dll
..\bin\cmdasy32.dll
..\bin\cmdvba32.dll
..\bin\umsw.dll
..\bin\irtl.dll
..\bin\hhctrl.ocx

[settings]
$LICENSE_OPTIONS=LM_LICENSE_FILE=..\bin\LICENSE.xml
$language=USA
$variation=USER
$keyboard=TRN_STD101
$enhanced_edit=all
$search_object=file_only
$search_descriptor=file_only
$no_valrep_check
$stop_on_div_by_zero=false
$putmess_logfile=msgframe.log
$store_booleans_as_false
$NEWLINE=CR
$ALLOW_FOREIGN_THREADS=1

[paths]
$ora=ora:ORCL11g|mccoig|mccoig
$def=$ora
$idf=$ora
$sys=$ora
$uuu=$ora

[files]
usys:*.frm=usys:*.frm
usys:*.dol=..\usys\*.dol
usys:*.urr=..\usys\*.urr
*.aps=..\*.aps
*.frm=..\*.frm
*.svc=..\*.svc
*.sql=..\utils\*.sql
*.exe=..\bin\*.exe
*.ico=..\icons\*.ico
*.esv=..\*.esv
*.prt=..\reports\*.*
*.txt=..\import
*.out=..\out
*.dot=..\doc

[entities]

[logicals]
CALLER_ID=
